$\alpha$와 $\beta$의 값이 같다.

$$\alpha = \beta$$

In [1]:
from sklearn.datasets import load_iris
iris = load_iris()
iris.data[0, :]

array([5.1, 3.5, 1.4, 0.2])

In [2]:
x2 = np.array([[4.9], [3.0], [1.4], [0.2]])

In [3]:
x2

array([[4.9],
       [3. ],
       [1.4],
       [0.2]])

In [4]:
x = np.array([[5.1, 3.5, 1.4, 0.2], [4.9, 3.0, 1.4, 0.2]])

In [5]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [6]:
x.T

array([[5.1, 4.9],
       [3.5, 3. ],
       [1.4, 1.4],
       [0.2, 0.2]])

In [7]:
x.T.T

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [15]:
x = np.array([[1],[2],[3]])

In [16]:
y = np.array([[4],[5],[6]])

In [10]:
x.T @ y

array([[32]])

In [17]:
np.dot(x.T, y)

array([[32]])

In [18]:
(x.T @ y)[0][0]

32

In [12]:
x = np.array([1,2,3])

In [13]:
y = np.array([4,5,6])

In [14]:
np.dot(x, y)

32

In [19]:
p = np.array([[1000000],[800000],[500000]])

In [20]:
n = np.array([[3],[4],[5]])

In [23]:
np.dot(p.T,n)[0][0]

8700000