In [1]:
from sklearn.datasets import load_boston

In [4]:
boston = load_boston()
X = boston.data
y = boston.target
A = X[:4, [0,4,5,6]]
b = y[:4]

In [3]:
A

array([[6.320e-03, 5.380e-01, 6.575e+00, 6.520e+01],
       [2.731e-02, 4.690e-01, 6.421e+00, 7.890e+01],
       [2.729e-02, 4.690e-01, 7.185e+00, 6.110e+01],
       [3.237e-02, 4.580e-01, 6.998e+00, 4.580e+01]])

In [5]:
b

array([24. , 21.6, 34.7, 33.4])

In [6]:
Ainv = np.linalg.inv(A)
x = np.dot(Ainv, b)
print(x)

[-3.12710043e+02 -1.15193942e+02  1.44996465e+01 -1.13259317e-01]


In [7]:
x, resid, rank, s = np.linalg.lstsq(X, y)
print(x)

[-9.28965170e-02  4.87149552e-02 -4.05997958e-03  2.85399882e+00
 -2.86843637e+00  5.92814778e+00 -7.26933458e-03 -9.68514157e-01
  1.71151128e-01 -9.39621540e-03 -3.92190926e-01  1.49056102e-02
 -4.16304471e-01]
